from __future__ import annotations

SYNTHETIC_JOBS = [
    {
        "job_id": 101,
        "title": "Senior Machine Learning Engineer",
        "company_name": "North Harbor AI",
        "salary_annual": 182000,
        "location": "New York, NY",
        "state": "NY",
        "experience_level": "Mid-Senior level",
        "work_type": "Remote",
        "text": "Build recommendation models, embeddings, and retrieval systems with Python, PyTorch, vector search, and AWS.",
    },
    {
        "job_id": 102,
        "title": "Product Data Scientist",
        "company_name": "Metric Canvas",
        "salary_annual": 156000,
        "location": "San Francisco, CA",
        "state": "CA",
        "experience_level": "Associate",
        "work_type": "Hybrid",
        "text": "Own experimentation, forecasting, funnel analytics, and executive storytelling across product teams.",
    },
    {
        "job_id": 103,
        "title": "Applied NLP Engineer",
        "company_name": "Signal Foundry",
        "salary_annual": 171000,
        "location": "Boston, MA",
        "state": "MA",
        "experience_level": "Mid-Senior level",
        "work_type": "Remote",
        "text": "Train NLP systems, search relevance pipelines, and semantic retrieval stacks using Python and transformers.",
    },
    {
        "job_id": 104,
        "title": "Analytics Engineer",
        "company_name": "Cinder Labs",
        "salary_annual": 138000,
        "location": "Austin, TX",
        "state": "TX",
        "experience_level": "Associate",
        "work_type": "On-site",
        "text": "Design data marts, dbt models, dashboards, KPI reporting, and SQL-heavy analytics workflows.",
    },
    {
        "job_id": 105,
        "title": "Backend Software Engineer, Recommendations",
        "company_name": "Circuit North",
        "salary_annual": 164000,
        "location": "Seattle, WA",
        "state": "WA",
        "experience_level": "Mid-Senior level",
        "work_type": "Hybrid",
        "text": "Ship APIs, ranking services, experiment infrastructure, and production Python services on AWS.",
    },
    {
        "job_id": 106,
        "title": "Staff Product Analyst",
        "company_name": "Aster Point",
        "salary_annual": 149000,
        "location": "Chicago, IL",
        "state": "IL",
        "experience_level": "Director",
        "work_type": "Remote",
        "text": "Drive executive decision support, growth analytics, lifecycle reporting, and product strategy.",
    },
]

FAKE_NAMES = [
    "Jordan Kim",
    "Priya Shah",
    "Maya Hernandez",
    "Ethan Brooks",
    "Leila Hassan",
    "Noah Patel",
    "Ava Morales",
    "Lucas Chen",
    "Sofia Bennett",
    "Owen Park",
]

FAKE_COMPANIES = [
    "Helio Metrics",
    "North Harbor AI",
    "Aster Point",
    "Circuit North",
    "Signal Foundry",
    "Blue Summit Labs",
    "Lattice Grove",
    "Quarry Logic",
    "Cinder Labs",
    "Metric Canvas",
]

FAKE_SCHOOLS = [
    "NYU",
    "Georgia Tech",
    "UC Berkeley",
    "University of Michigan",
    "Northeastern",
    "Carnegie Mellon",
    "Columbia",
    "UT Austin",
]

TRACK_TITLES = {
    "Machine Learning": [
        "Machine Learning Engineer",
        "Applied Scientist",
        "NLP Engineer",
    ],
    "Data Science": ["Data Scientist", "Product Data Scientist", "Decision Scientist"],
    "Software Engineering": [
        "Backend Software Engineer",
        "Platform Engineer",
        "Systems Engineer",
    ],
    "Analytics": [
        "Analytics Engineer",
        "Senior Analyst",
        "Business Intelligence Analyst",
    ],
    "Product / Strategy": [
        "Product Strategy Lead",
        "Growth Strategist",
        "Product Analyst",
    ],
    "Human Resources": [
        "People Operations Manager",
        "Talent Acquisition Partner",
        "HR Generalist",
    ],
    "Finance / Accounting": [
        "Financial Analyst",
        "Accounting Manager",
        "FP&A Analyst",
    ],
    "Marketing": [
        "Marketing Manager",
        "Growth Marketing Specialist",
        "Lifecycle Marketing Lead",
    ],
    "Sales / Customer Success": [
        "Customer Success Manager",
        "Account Executive",
        "Revenue Operations Analyst",
    ],
    "Operations / Administration": [
        "Operations Manager",
        "Administrative Coordinator",
        "Business Operations Associate",
    ],
}

TRACK_INITIATIVES = {
    "Machine Learning": [
        "retrieval ranking stack",
        "candidate matching pipeline",
        "semantic search service",
        "feature-rich recommendation workflow",
    ],
    "Data Science": [
        "experiment measurement layer",
        "forecasting and scenario planning workflow",
        "growth analytics operating model",
        "decision support dashboard suite",
    ],
    "Software Engineering": [
        "distributed service layer",
        "platform reliability program",
        "event-driven API stack",
        "deployment automation pipeline",
    ],
    "Analytics": [
        "executive KPI layer",
        "warehouse modeling program",
        "self-serve reporting surface",
        "business performance review workflow",
    ],
    "Product / Strategy": [
        "market expansion narrative",
        "cross-functional planning rhythm",
        "growth prioritization framework",
        "portfolio strategy review",
    ],
    "Human Resources": [
        "structured hiring workflow",
        "onboarding and retention program",
        "employee relations intake process",
        "manager enablement cadence",
    ],
    "Finance / Accounting": [
        "monthly close workflow",
        "budget variance review",
        "forecast planning model",
        "audit readiness program",
    ],
    "Marketing": [
        "lifecycle campaign calendar",
        "brand performance review",
        "content measurement workflow",
        "demand generation program",
    ],
    "Sales / Customer Success": [
        "account health review",
        "renewal planning workflow",
        "pipeline inspection cadence",
        "customer expansion program",
    ],
    "Operations / Administration": [
        "vendor management process",
        "office operations rhythm",
        "executive scheduling workflow",
        "cross-team coordination system",
    ],
}

TRACK_PROJECTS = {
    "Machine Learning": [
        "search relevance simulator",
        "embedding quality scorecard",
        "model rollout control tower",
    ],
    "Data Science": [
        "retention diagnostic notebook",
        "experimentation intake rubric",
        "forecast variance monitor",
    ],
    "Software Engineering": [
        "API latency watchtower",
        "service dependency mapper",
        "release health dashboard",
    ],
    "Analytics": [
        "metric definition library",
        "reporting coverage audit",
        "dashboard adoption tracker",
    ],
    "Product / Strategy": [
        "market signal brief",
        "roadmap tradeoff memo series",
        "customer segment sizing model",
    ],
    "Human Resources": [
        "talent funnel scorecard",
        "onboarding journey map",
        "employee feedback tracker",
    ],
    "Finance / Accounting": [
        "budget variance model",
        "monthly close checklist",
        "cash planning dashboard",
    ],
    "Marketing": [
        "campaign performance brief",
        "content calendar scorecard",
        "audience segment review",
    ],
    "Sales / Customer Success": [
        "renewal risk dashboard",
        "account planning toolkit",
        "customer health review",
    ],
    "Operations / Administration": [
        "vendor tracker",
        "office workflow audit",
        "meeting cadence planner",
    ],
}

TRACK_METRICS = {
    "Machine Learning": "matching quality",
    "Data Science": "forecast accuracy",
    "Software Engineering": "service reliability",
    "Analytics": "report turnaround time",
    "Product / Strategy": "planning clarity",
    "Human Resources": "hiring cycle time",
    "Finance / Accounting": "forecast accuracy",
    "Marketing": "campaign conversion",
    "Sales / Customer Success": "renewal readiness",
    "Operations / Administration": "process turnaround time",
}

SAMPLE_RESUME_SPECS = [
    (
        "Alex Rivera",
        "Machine Learning",
        "Senior Machine Learning Engineer",
        "Senior",
        "New York, NY",
        "marketplace ranking",
        "excellent",
    ),
    (
        "Priya Shah",
        "Data Science",
        "Product Data Scientist",
        "Senior",
        "San Francisco, CA",
        "consumer growth",
        "excellent",
    ),
    (
        "Maya Hernandez",
        "Software Engineering",
        "Backend Platform Engineer",
        "Mid",
        "Austin, TX",
        "payments infrastructure",
        "excellent",
    ),
    (
        "Ethan Brooks",
        "Analytics",
        "Analytics Engineer",
        "Mid",
        "Chicago, IL",
        "subscription metrics",
        "excellent",
    ),
    (
        "Leila Hassan",
        "Product / Strategy",
        "Product Strategy Lead",
        "Lead / Executive",
        "Seattle, WA",
        "B2B pricing",
        "excellent",
    ),
    (
        "Noah Patel",
        "Human Resources",
        "People Operations Manager",
        "Senior",
        "Boston, MA",
        "distributed teams",
        "excellent",
    ),
    (
        "Ava Morales",
        "Finance / Accounting",
        "FP&A Manager",
        "Senior",
        "Denver, CO",
        "SaaS planning",
        "excellent",
    ),
    (
        "Lucas Chen",
        "Marketing",
        "Lifecycle Marketing Lead",
        "Senior",
        "Remote",
        "B2B retention",
        "excellent",
    ),
    (
        "Sofia Bennett",
        "Sales / Customer Success",
        "Enterprise Customer Success Manager",
        "Senior",
        "Atlanta, GA",
        "cloud accounts",
        "excellent",
    ),
    (
        "Owen Park",
        "Operations / Administration",
        "Business Operations Manager",
        "Mid",
        "Los Angeles, CA",
        "multi-site operations",
        "solid",
    ),
    (
        "Nadia Okafor",
        "Healthcare / Clinical",
        "Clinical Quality Improvement Nurse",
        "Senior",
        "Philadelphia, PA",
        "cardiology care",
        "excellent",
    ),
    (
        "Grace Lee",
        "Education / Teaching",
        "Instructional Coach",
        "Senior",
        "Queens, NY",
        "middle school math",
        "excellent",
    ),
    (
        "Marcus Reed",
        "Legal / Compliance",
        "Privacy Compliance Counsel",
        "Senior",
        "Washington, DC",
        "health technology",
        "excellent",
    ),
    (
        "Iris Wong",
        "Design / Creative",
        "Senior Product Designer",
        "Senior",
        "Portland, OR",
        "mobile onboarding",
        "excellent",
    ),
    (
        "Caleb Morgan",
        "Engineering / Hardware",
        "Mechanical Design Engineer",
        "Mid",
        "Detroit, MI",
        "EV battery systems",
        "excellent",
    ),
    (
        "Hannah Stein",
        "Research / Academia",
        "Research Scientist",
        "Senior",
        "Cambridge, MA",
        "computational biology",
        "excellent",
    ),
    (
        "Diego Alvarez",
        "Public Sector / Policy",
        "Policy Analyst",
        "Mid",
        "Sacramento, CA",
        "housing programs",
        "solid",
    ),
    (
        "Emma Johnson",
        "Hospitality / Service",
        "Hotel Operations Manager",
        "Mid",
        "Miami, FL",
        "luxury guest services",
        "solid",
    ),
    (
        "Sam Taylor",
        "Machine Learning",
        "Computer Vision Engineer",
        "Mid",
        "Pittsburgh, PA",
        "manufacturing inspection",
        "solid",
    ),
    (
        "Rina Mehta",
        "Data Science",
        "Decision Scientist",
        "Mid",
        "Remote",
        "risk analytics",
        "solid",
    ),
    (
        "Theo Martin",
        "Software Engineering",
        "Full Stack Engineer",
        "Associate",
        "Raleigh, NC",
        "healthcare scheduling",
        "solid",
    ),
    (
        "Camila Torres",
        "Analytics",
        "Business Intelligence Analyst",
        "Associate",
        "Dallas, TX",
        "retail inventory",
        "solid",
    ),
    (
        "Jasper Nguyen",
        "Product / Strategy",
        "Associate Product Manager",
        "Associate",
        "San Jose, CA",
        "developer tools",
        "solid",
    ),
    (
        "Mina Ali",
        "Human Resources",
        "Talent Acquisition Partner",
        "Mid",
        "Minneapolis, MN",
        "clinical hiring",
        "solid",
    ),
    (
        "Ben Carter",
        "Finance / Accounting",
        "Senior Accountant",
        "Mid",
        "Charlotte, NC",
        "manufacturing close",
        "solid",
    ),
    (
        "Talia Green",
        "Marketing",
        "Demand Generation Manager",
        "Mid",
        "Phoenix, AZ",
        "cybersecurity pipeline",
        "solid",
    ),
    (
        "Andre Wilson",
        "Sales / Customer Success",
        "Account Executive",
        "Mid",
        "Nashville, TN",
        "mid-market sales",
        "solid",
    ),
    (
        "Lena Brooks",
        "Operations / Administration",
        "Executive Assistant",
        "Associate",
        "New York, NY",
        "founder support",
        "solid",
    ),
    (
        "Mei Lin",
        "Healthcare / Clinical",
        "Physical Therapist",
        "Mid",
        "San Diego, CA",
        "orthopedic rehab",
        "solid",
    ),
    (
        "Patrick O'Neill",
        "Education / Teaching",
        "High School Science Teacher",
        "Mid",
        "Columbus, OH",
        "project-based learning",
        "solid",
    ),
    (
        "Alina Petrova",
        "Legal / Compliance",
        "Contracts Manager",
        "Mid",
        "Remote",
        "vendor agreements",
        "solid",
    ),
    (
        "Jonah Weiss",
        "Design / Creative",
        "Brand Designer",
        "Mid",
        "Brooklyn, NY",
        "consumer packaging",
        "solid",
    ),
    (
        "Sasha Kim",
        "Engineering / Hardware",
        "Electrical Engineer",
        "Associate",
        "San Jose, CA",
        "sensor boards",
        "solid",
    ),
    (
        "Omar Farouk",
        "Research / Academia",
        "Postdoctoral Researcher",
        "Mid",
        "Ann Arbor, MI",
        "urban mobility",
        "solid",
    ),
    (
        "Claire Dubois",
        "Public Sector / Policy",
        "Program Evaluation Specialist",
        "Mid",
        "Boston, MA",
        "workforce grants",
        "solid",
    ),
    (
        "Mateo Garcia",
        "Hospitality / Service",
        "Restaurant General Manager",
        "Mid",
        "Orlando, FL",
        "high-volume dining",
        "solid",
    ),
    (
        "Yuki Tanaka",
        "Machine Learning",
        "Junior ML Engineer",
        "Associate",
        "Seattle, WA",
        "recommendation prototypes",
        "solid",
    ),
    (
        "Fatima Khan",
        "Data Science",
        "Data Analyst",
        "Associate",
        "Houston, TX",
        "energy operations",
        "solid",
    ),
    (
        "Mason Wright",
        "Software Engineering",
        "Software Engineering Intern",
        "Intern / Entry",
        "Madison, WI",
        "campus tools",
        "thin",
    ),
    (
        "Elena Rossi",
        "Analytics",
        "Junior Analyst",
        "Intern / Entry",
        "Tampa, FL",
        "dashboard support",
        "thin",
    ),
    (
        "Daniel Kim",
        "Product / Strategy",
        "Product Intern",
        "Intern / Entry",
        "Remote",
        "student marketplace",
        "thin",
    ),
    (
        "Aisha Brown",
        "Human Resources",
        "HR Coordinator",
        "Associate",
        "Baltimore, MD",
        "onboarding operations",
        "thin",
    ),
    (
        "Liam Evans",
        "Finance / Accounting",
        "Accounting Assistant",
        "Associate",
        "Cleveland, OH",
        "accounts payable",
        "thin",
    ),
    (
        "Nora Murphy",
        "Marketing",
        "Social Media Coordinator",
        "Associate",
        "Salt Lake City, UT",
        "local campaigns",
        "thin",
    ),
    (
        "Luis Romero",
        "Sales / Customer Success",
        "Sales Development Representative",
        "Associate",
        "San Antonio, TX",
        "outbound prospecting",
        "thin",
    ),
    (
        "Zara Ahmed",
        "Operations / Administration",
        "Administrative Coordinator",
        "Associate",
        "Las Vegas, NV",
        "office scheduling",
        "thin",
    ),
    (
        "Victor Chen",
        "Healthcare / Clinical",
        "Medical Assistant",
        "Associate",
        "Fresno, CA",
        "primary care",
        "thin",
    ),
    (
        "Molly Adams",
        "Education / Teaching",
        "Teaching Assistant",
        "Intern / Entry",
        "Ithaca, NY",
        "undergraduate tutoring",
        "thin",
    ),
    (
        "Rachel Cohen",
        "Legal / Compliance",
        "Paralegal",
        "Associate",
        "Newark, NJ",
        "litigation support",
        "thin",
    ),
    (
        "Chris Miller",
        "Design / Creative",
        "UX Design Intern",
        "Intern / Entry",
        "Remote",
        "portfolio redesign",
        "thin",
    ),
]

SAMPLE_RESUME_SOURCE_HELP = """This sample resume is generated by `app.demo.samples`.

The profile library is `SAMPLE_RESUME_SPECS` in `app.demo.sample_data`, and the selected profile is rendered by `generate_premade_sample_resume()`. Clicking "Load random sample resume" calls `random_premade_sample_resume(jobs, previous_index)`, which chooses one profile, avoids repeating the previously loaded profile when possible, and stores the rendered text in Streamlit session state.

Generation details: the renderer uses a Python f-string resume template, deterministic NumPy values seeded from the selected profile tuple, local fake schools/company fallbacks, track-specific skills, role seniority, location, and domain cues.

Job-catalog context: company and market examples come from `choose_market_examples()`. If `data/processed/jobs.parquet` exists, `app.runtime.cache.load_jobs()` reads that processed job catalog. That parquet is generated from the Kaggle LinkedIn job postings data by running `uv run python scripts/preprocess_data.py`. If the parquet is missing, the app uses the in-code `SYNTHETIC_JOBS` sample role catalog.

These resumes are synthetic demo examples for trying the workflow, not real candidate data."""

SAMPLE_RESUME_SOURCE_SUMMARY = (
    "Sample resumes are synthetic demo examples generated from local templates "
    "and seeded with role, skill, location, and job-catalog cues. They are not "
    "real candidate data."
)
