from __future__ import annotations

import re

TRACK_KEYWORDS = {
    "Machine Learning": [
        "machine learning",
        "ml",
        "pytorch",
        "tensorflow",
        "nlp",
        "embedding",
        "faiss",
    ],
    "Data Science": [
        "data science",
        "experimentation",
        "statistics",
        "modeling",
        "python",
        "pandas",
    ],
    "Software Engineering": [
        "software",
        "backend",
        "api",
        "distributed",
        "docker",
        "aws",
        "systems",
    ],
    "Analytics": ["analytics", "dashboard", "sql", "bi", "reporting", "tableau"],
    "Product / Strategy": [
        "product",
        "roadmap",
        "market",
        "strategy",
        "stakeholder",
        "growth",
    ],
    "Human Resources": [
        "human resources",
        "hr",
        "talent",
        "recruiting",
        "benefits",
        "employee relations",
        "people operations",
    ],
    "Finance / Accounting": [
        "finance",
        "accounting",
        "financial",
        "budget",
        "forecast",
        "audit",
        "fp&a",
    ],
    "Marketing": [
        "marketing",
        "campaign",
        "brand",
        "content",
        "demand generation",
        "seo",
        "crm",
    ],
    "Sales / Customer Success": [
        "sales",
        "account",
        "customer success",
        "client",
        "pipeline",
        "renewal",
        "quota",
    ],
    "Operations / Administration": [
        "operations",
        "office",
        "administrative",
        "process",
        "vendor",
        "scheduling",
        "coordination",
    ],
    "Healthcare / Clinical": [
        "nursing",
        "nurse",
        "clinical",
        "patient",
        "physician",
        "hospital",
        "medical",
        "pharmacy",
        "therapist",
        "diagnosis",
        "ehr",
        "epic",
        "cerner",
        "rn ",
        "ms n",
        "phlebotomy",
    ],
    "Education / Teaching": [
        "teaching",
        "teacher",
        "curriculum",
        "classroom",
        "professor",
        "lecturer",
        "instructional",
        "lesson plan",
        "k-12",
        "pedagogy",
        "student outcomes",
        "edtech",
        "tutor",
    ],
    "Legal / Compliance": [
        "attorney",
        "lawyer",
        "litigation",
        "paralegal",
        "contract review",
        "general counsel",
        "regulatory",
        "compliance",
        "legal research",
        "deposition",
        "law firm",
        "juris doctor",
    ],
    "Design / Creative": [
        "designer",
        "ux",
        "ui",
        "user experience",
        "user interface",
        "figma",
        "sketch",
        "photoshop",
        "illustrator",
        "branding",
        "wireframe",
        "prototype",
        "visual design",
        "art direction",
        "creative direction",
    ],
    "Engineering / Hardware": [
        "mechanical engineer",
        "civil engineer",
        "electrical engineer",
        "structural",
        "manufacturing",
        "cad",
        "solidworks",
        "autocad",
        "fea",
        "pcb",
        "embedded systems",
        "firmware",
        "hardware",
        "matlab",
    ],
    "Research / Academia": [
        "research",
        "publication",
        "peer-review",
        "peer review",
        "laboratory",
        "postdoc",
        "phd",
        "dissertation",
        "principal investigator",
        "grant",
        "conference",
        "abstract",
        "journal",
    ],
    "Public Sector / Policy": [
        "government",
        "federal agency",
        "policy analysis",
        "civic",
        "public administration",
        "nonprofit",
        "advocacy",
        "legislative",
        "constituent",
        "municipal",
        "public sector",
        "ngo",
    ],
    "Hospitality / Service": [
        "hospitality",
        "restaurant",
        "hotel",
        "concierge",
        "barista",
        "chef",
        "food service",
        "front of house",
        "back of house",
        "guest services",
        "front desk",
        "events coordinator",
    ],
}

SKILL_GROUPS = {
    "Python": ["python"],
    "SQL": ["sql", "postgres", "snowflake"],
    "Predictive Modeling": [
        "machine learning",
        "model",
        "xgboost",
        "pytorch",
        "tensorflow",
        "sklearn",
    ],
    "NLP / Retrieval": ["nlp", "llm", "embedding", "retrieval", "faiss", "vector"],
    "Cloud / Ops": ["aws", "gcp", "docker", "kubernetes", "airflow"],
    "Product Sense": ["experiment", "stakeholder", "roadmap", "product", "growth"],
    "People Operations": ["hr", "talent", "recruiting", "benefits", "employee"],
    "Financial Planning": ["finance", "accounting", "budget", "forecast", "audit"],
    "Go-to-Market": ["marketing", "sales", "customer", "campaign", "account"],
}

SENIORITY_MULTIPLIER = {
    "Intern / Entry": 0.72,
    "Associate": 0.9,
    "Mid": 1.0,
    "Senior": 1.18,
    "Lead / Executive": 1.35,
}

TRACK_SKILLS = {
    "Machine Learning": [
        "Python",
        "PyTorch",
        "Vector Search",
        "NLP",
        "Embeddings",
        "SQL",
        "AWS",
        "Docker",
    ],
    "Data Science": [
        "Python",
        "pandas",
        "SQL",
        "Experimentation",
        "Forecasting",
        "A/B Testing",
        "Statistics",
    ],
    "Software Engineering": [
        "Python",
        "APIs",
        "Docker",
        "AWS",
        "Distributed Systems",
        "Postgres",
        "CI/CD",
    ],
    "Analytics": [
        "SQL",
        "dbt",
        "Looker",
        "Dashboarding",
        "KPIs",
        "Pandas",
        "Data Modeling",
    ],
    "Product / Strategy": [
        "Market Analysis",
        "Stakeholder Mgmt",
        "Roadmapping",
        "SQL",
        "Growth",
        "Presentation",
    ],
    "Human Resources": [
        "Talent Acquisition",
        "Employee Relations",
        "Onboarding",
        "HRIS",
        "Benefits",
        "Workforce Planning",
    ],
    "Finance / Accounting": [
        "Budgeting",
        "Forecasting",
        "Accounting",
        "Financial Reporting",
        "Excel",
        "Audit Support",
    ],
    "Marketing": [
        "Campaign Strategy",
        "Content",
        "CRM",
        "SEO",
        "Lifecycle Marketing",
        "Analytics",
    ],
    "Sales / Customer Success": [
        "Account Management",
        "Pipeline Review",
        "Renewals",
        "Customer Health",
        "CRM",
        "Executive Communication",
    ],
    "Operations / Administration": [
        "Process Improvement",
        "Vendor Management",
        "Scheduling",
        "Office Operations",
        "Documentation",
        "Stakeholder Support",
    ],
}

SAMPLE_FIELD_SKILLS = {
    "Machine Learning": [
        "Python",
        "PyTorch",
        "Feature Stores",
        "Vector Search",
        "Experiment Design",
        "Model Monitoring",
        "AWS",
        "Docker",
    ],
    "Data Science": [
        "Python",
        "SQL",
        "Causal Inference",
        "A/B Testing",
        "Forecasting",
        "Tableau",
        "Stakeholder Storytelling",
    ],
    "Software Engineering": [
        "Python",
        "Go",
        "Postgres",
        "Kubernetes",
        "Distributed Systems",
        "Observability",
        "CI/CD",
    ],
    "Analytics": [
        "SQL",
        "dbt",
        "Looker",
        "Data Modeling",
        "Metric Governance",
        "Python",
        "Executive Reporting",
    ],
    "Product / Strategy": [
        "Roadmapping",
        "Market Sizing",
        "Customer Research",
        "SQL",
        "Pricing",
        "Executive Communication",
        "Experiment Planning",
    ],
    "Human Resources": [
        "Talent Acquisition",
        "Workday",
        "Employee Relations",
        "Compensation Planning",
        "DEI Programs",
        "Manager Coaching",
        "People Analytics",
    ],
    "Finance / Accounting": [
        "FP&A",
        "Budgeting",
        "Revenue Recognition",
        "Excel",
        "NetSuite",
        "Audit Readiness",
        "Board Reporting",
    ],
    "Marketing": [
        "Lifecycle Marketing",
        "HubSpot",
        "Paid Social",
        "SEO",
        "Content Strategy",
        "Attribution",
        "Customer Segmentation",
    ],
    "Sales / Customer Success": [
        "Salesforce",
        "MEDDICC",
        "Pipeline Forecasting",
        "Renewal Strategy",
        "Executive Business Reviews",
        "Customer Health",
        "Revenue Operations",
    ],
    "Operations / Administration": [
        "Vendor Management",
        "Process Improvement",
        "Executive Support",
        "Facilities",
        "Procurement",
        "Documentation",
        "Scheduling",
    ],
    "Healthcare / Clinical": [
        "Epic",
        "Care Coordination",
        "Patient Safety",
        "Clinical Documentation",
        "Quality Improvement",
        "HIPAA",
        "Interdisciplinary Rounds",
    ],
    "Education / Teaching": [
        "Curriculum Design",
        "Differentiated Instruction",
        "Student Assessment",
        "Learning Analytics",
        "Classroom Management",
        "IEP Support",
        "Instructional Coaching",
    ],
    "Legal / Compliance": [
        "Contract Review",
        "Regulatory Analysis",
        "Privacy Compliance",
        "Negotiation",
        "Policy Drafting",
        "Risk Assessment",
        "Legal Research",
    ],
    "Design / Creative": [
        "Figma",
        "Design Systems",
        "User Research",
        "Prototyping",
        "Accessibility",
        "Visual Design",
        "Content Strategy",
    ],
    "Engineering / Hardware": [
        "SolidWorks",
        "DFMEA",
        "Manufacturing Transfer",
        "Tolerance Analysis",
        "Test Fixtures",
        "Supplier Quality",
        "MATLAB",
    ],
    "Research / Academia": [
        "Grant Writing",
        "Statistical Modeling",
        "IRB Protocols",
        "Peer-Reviewed Publications",
        "R",
        "Experimental Design",
        "Conference Presentations",
    ],
    "Public Sector / Policy": [
        "Policy Analysis",
        "Program Evaluation",
        "Stakeholder Engagement",
        "Legislative Research",
        "Grant Reporting",
        "Public Dashboards",
        "Community Outreach",
    ],
    "Hospitality / Service": [
        "Guest Experience",
        "Team Scheduling",
        "Inventory Control",
        "POS Systems",
        "Event Operations",
        "Vendor Coordination",
        "Service Recovery",
    ],
}

SECTION_ALIASES = {
    "Summary": ["summary", "professional summary", "profile"],
    "Experience": [
        "experience",
        "professional experience",
        "work experience",
        "employment history",
    ],
    "Projects": [
        "projects",
        "selected projects",
        "research publications",
        "publications",
    ],
    "Education": ["education"],
    "Skills": ["skills", "core skills", "technical skills"],
}

PRESTIGIOUS_COMPANY_TOKENS = (
    "google",
    "alphabet",
    "apple",
    "microsoft",
    "meta",
    "facebook",
    "amazon",
    "netflix",
    "openai",
    "anthropic",
    "deepmind",
    "nvidia",
    "stripe",
    "databricks",
    "snowflake",
    "palantir",
    "spacex",
    "tesla",
    "airbnb",
    "uber",
    "linkedin",
    "tiktok",
    "bytedance",
    "mckinsey",
    "boston consulting",
    "bain & company",
    "bain and company",
    "goldman sachs",
    "morgan stanley",
    "j.p. morgan",
    "jpmorgan",
    "blackstone",
    "blackrock",
    "citadel",
    "jane street",
    "two sigma",
    "renaissance technologies",
    "de shaw",
    "jump trading",
    "hudson river trading",
    "point72",
    "mayo clinic",
    "johns hopkins",
    "cleveland clinic",
    "memorial sloan kettering",
    "massachusetts general",
    "stanford health",
    "cravath",
    "wachtell",
    "sullivan & cromwell",
    "latham & watkins",
    "skadden",
    "kirkland & ellis",
    "davis polk",
    "nasa",
    "lawrence livermore",
    "los alamos",
    "fermilab",
    "bell labs",
    "national institutes of health",
)

PRESTIGIOUS_EDUCATION_TOKENS = (
    "stanford university",
    "stanford",
    "massachusetts institute of technology",
    "mit",
    "harvard university",
    "harvard",
    "princeton university",
    "princeton",
    "yale university",
    "yale",
    "caltech",
    "california institute of technology",
    "uc berkeley",
    "university of california berkeley",
    "berkeley",
    "carnegie mellon",
    "cmu",
    "university of chicago",
    "columbia university",
    "columbia",
    "cornell university",
    "cornell",
    "university of pennsylvania",
    "upenn",
    "oxford",
    "university of oxford",
    "cambridge",
    "university of cambridge",
    "eth zurich",
    "tsinghua university",
    "tsinghua",
    "peking university",
)

RIGOROUS_TITLE_TOKENS = (
    "software engineer",
    "machine learning engineer",
    "research scientist",
    "data scientist",
    "research engineer",
    "applied scientist",
    "member of technical staff",
    "technical staff",
    "staff research scientist",
    "physician",
    "surgeon",
    "resident",
    "attending",
    "attorney",
    "lawyer",
    "associate attorney",
    "investment banker",
    "investment banking",
    "quantitative researcher",
    "quant trader",
    "quantitative analyst",
    "actuary",
    "tax lawyer",
    "principal",
    "staff engineer",
    "senior engineer",
    "senior scientist",
    "director",
    "chief",
    "vice president",
    "head of",
    "fellow",
    "professor",
    "postdoctoral",
    "postdoc",
)

LOW_RIGOR_TITLE_TOKENS = (
    "cashier",
    "server",
    "barista",
    "waiter",
    "waitress",
    "bartender",
    "retail associate",
    "sales associate",
    "store associate",
    "receptionist",
    "host",
    "hostess",
    "cleaner",
    "janitor",
    "tutor",
    "babysitter",
    "delivery driver",
    "lifeguard",
    "camp counselor",
    "front desk",
    "stocker",
    "dishwasher",
    "valet",
)

VAGUE_PHRASES = (
    "worked on",
    "helped with",
    "involved in",
    "responsible for",
    "various projects",
    "many projects",
    "assisted with",
    "participated in",
    "contributed to",
    "exposed to",
    "familiar with",
)

ACTION_VERBS = (
    "built",
    "shipped",
    "deployed",
    "launched",
    "led",
    "scaled",
    "architected",
    "optimized",
    "reduced",
    "increased",
    "automated",
    "migrated",
    "owned",
    "designed",
    "implemented",
    "delivered",
    "developed",
    "drove",
    "spearheaded",
    "authored",
)

SCHOOL_PROJECT_MARKERS = (
    "course project",
    "class project",
    "coursework",
    "capstone",
    "thesis",
    "hackathon",
    "university project",
    "academic project",
    "school project",
    "for cs",
    "csci",
    "cs10",
    "cs20",
    "cs30",
    "cs40",
    "as part of cs",
    "team project for",
    "homework",
)

IMPACT_REGEX = re.compile(
    r"(?:\$\s?\d[\d,\.]*\s?(?:k|m|million|billion|b)?\b"
    r"|\b\d+(?:\.\d+)?\s?%"
    r"|\b\d+(?:\.\d+)?\s?(?:x|×)\b"
    r"|\b\d{2,}\s?(?:users|customers|clients|requests|qps|ms|hours|days|weeks|months|years|reps|teams|engineers|orders|tickets|sessions|deals|contracts|patients|students)\b)",
    re.IGNORECASE,
)

_MONTHS = (
    "jan",
    "feb",
    "mar",
    "apr",
    "may",
    "jun",
    "jul",
    "aug",
    "sep",
    "sept",
    "oct",
    "nov",
    "dec",
)

_MONTH_INDEX = {
    "jan": 1,
    "feb": 2,
    "mar": 3,
    "apr": 4,
    "may": 5,
    "jun": 6,
    "jul": 7,
    "aug": 8,
    "sep": 9,
    "sept": 9,
    "oct": 10,
    "nov": 11,
    "dec": 12,
}

DATE_RANGE_REGEX = re.compile(
    r"(?:(?P<m1>" + "|".join(_MONTHS) + r")\s*)?"
    r"(?P<y1>20\d{2}|19\d{2})(?:[./](?P<n1>\d{1,2}))?\s*[-–—]+\s*"
    r"(?:\(?\s*(?P<present>present|current|now|today|expected)\s*\)?|"
    r"(?:(?P<m2>" + "|".join(_MONTHS) + r")\s*)?"
    r"(?P<y2>20\d{2}|19\d{2})(?:[./](?P<n2>\d{1,2}))?)",
    re.IGNORECASE,
)

WORK_SECTION_LABELS = {
    "experience",
    "professional experience",
    "work experience",
    "employment",
    "employment history",
    "career history",
    "internships",
}

NON_WORK_SECTION_LABELS = {
    "education",
    "honors",
    "honors and awards",
    "awards",
    "certifications",
    "licenses",
    "skills",
    "technical skills",
    "projects",
    "selected projects",
    "publications",
    "activities",
}

NON_WORK_DATE_TOKENS = (
    "honor",
    "dean's list",
    "deans list",
    "award",
    "scholarship",
    "education",
    "university",
    "college",
    "school",
    "b.s.",
    "b.a.",
    "m.s.",
    "m.a.",
    "ph.d",
    "gpa",
    "graduation",
    "expected",
    "coursework",
    "certification",
    "license",
)

FALLBACK_TRACK_SKILLS = [
    "Communication",
    "Project Management",
    "Stakeholder Engagement",
    "Process Improvement",
    "Documentation",
    "Problem Solving",
]
